spring.application.name=url-shortener

spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=Tharun@2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
